services:
  - type: web
    name: nitrodynamics-kanban
    env: node
    nodeVersion: 18.x
    buildCommand: export NODE_OPTIONS=--openssl-legacy-provider && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --openssl-legacy-provider
    plan: free 